-- 写真テーブル作成
CREATE TABLE pictures (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    family_id INT UNSIGNED NOT NULL,
    uploaded_by INT UNSIGNED NOT NULL,
    title VARCHAR(255),
    description TEXT,
    file_path VARCHAR(500) NOT NULL,
    thumbnail_path VARCHAR(500),
    file_size INT UNSIGNED,
    mime_type VARCHAR(100),
    width INT UNSIGNED,
    height INT UNSIGNED,
    taken_date DATETIME COMMENT '撮影日時（EXIFから自動抽出または手動入力）',
    category_id INT UNSIGNED COMMENT 'NULL許可、未分類カテゴリに自動振り分け',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '1: 有効, 0: 削除済み（ごみ箱）',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (uploaded_by) REFERENCES users(id),
    FOREIGN KEY (category_id) REFERENCES categories(id),
    INDEX idx_family_id (family_id),
    INDEX idx_uploaded_by (uploaded_by),
    INDEX idx_category_id (category_id),
    INDEX idx_status (status),
    INDEX idx_taken_date (taken_date),
    INDEX idx_family_status (family_id, status),
    INDEX idx_family_category (family_id, category_id),
    INDEX idx_family_taken_date (family_id, taken_date),
    INDEX idx_search (family_id, status, taken_date, category_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;